# --- !Ups

create table CLASSES (CLASS_ID SERIAL PRIMARY KEY, NAME TEXT NOT NULL);
create table RACES (RACE_ID SERIAL PRIMARY KEY, NAME TEXT NOT NULL);
create table SPELLS (SPELL_ID SERIAL PRIMARY KEY, NAME TEXT NOT NULL, KIND TEXT NOT NULL, TIME TEXT NOT NULL, RANGE TEXT NOT NULL,COMPONENTS TEXT NOT NULL,DURATION TEXT NOT NULL,BODY TEXT NOT NULL);

# --- !Downs

drop table SPELLS;
drop table RACES;
drop table CLASSES;

